version: '3.8'

services:
  api-gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - logging-service
      - notification-service
      - kafka
      - postgres
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: auth-service
    depends_on:
      - kafka
      - postgres
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  logging-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: logging-service
    depends_on:
      - kafka
      - postgres
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  notification-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: notification-service
    depends_on:
      - kafka
      - postgres
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
